### ISSUE TITLE
TCP.sum is not recomputed after _update_fields is called on an upper layer

### ISSUE THREAD

**Issue by ebertland** [mike01/pypacker#37] opened 2017-10-20 00:25 UTC
In a custom layer5 protocol, I added a header "length" in the __hdr__ tuple of tuples. It is fixed size (2 octets) and I used the FIELD_FLAG_AUTOUPDATE option. I wrote the code for _update_fields (for current HEAD of master) and for bin() (version 4.0) to calculate the length of the upper_layer body and store that in self.length. For both, the correct length is written to the header of my custom protocol.

The problem is that the TCP.sum is never recalculated to account for the updated length field. I traced the calls, and I see that TCP._update_fields() is only called once and it is before the call to my custom protocol's _update_fields() (or bin() in the case of version 4.0).

Can you recommend an example where a layer567 protocol is layered above TCP, and it has automatically updated simple header fields? I am not doing anything complicated that requires dynamic fields, deactivated fields, or trigger lists.

**Comment by mike01** [comment] 2017-10-21 00:57
Seems to be a regression when _update_fields() was newly introduced. A quick fix would be to force checksum recalculation by changing the TCP header like "tcp.sum = tcp.sum"

**Comment by mike01** [comment] 2017-10-28 17:50
Should be fixed now in current master branch

**Comment by mike01** [comment] 2017-12-16 01:58
Response timeout, closing ticket.

**Closed by mike01** 2017-12-16 01:58 UTC
