### ISSUE TITLE
ImportError: cannot import name ppcap

### ISSUE THREAD

**Issue by iamgroot42** [mike01/pypacker#35] opened 2017-09-30 14:45 UTC
----> 1 from pypacker import ppcap
      2 from pypacker.layer12 import ethernet
      3 from pypacker.layer3 import ip
      4 from pypacker.layer4 import tcp
      5 

ImportError: cannot import name ppcap

**Comment by mike01** [comment] 2017-10-02 12:56
Hm strange, I can't reproduce the error. Is pypacker correctly installed?
python setup.py install (using python 3 interpreter)

**Comment by mike01** [comment] 2017-10-28 17:51
Closing due response timeout

**Closed by mike01** 2017-10-28 17:51 UTC
